{% set name = "pydantic-units" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SimonBoothroyd/pydantic-units/archive/{{ version }}.tar.gz
  sha256: 7261cf12c400af0c8953ecaaf3af40fcb0ce929fc70c3ea0601783e03ec5b07a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.10
    - pip
    - setuptools >=61.0
    - setuptools_scm >=8
  run:
    - python >=3.10
    - pydantic
    - openmm

test:
  imports:
    - pydantic_units
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/SimonBoothroyd/pydantic-units
  summary: 'Support for OpenMM units as pydantic fields'
  description: |
    A framework that aims to offer a convenient way to work with OpenMM units in 
    Pydantic models, in a way that is backwards compatible with both Pydantic v1 and v2.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://simonboothroyd.github.io/pydantic-units/latest/
  dev_url: https://github.com/SimonBoothroyd/pydantic-units

extra:
  recipe-maintainers:
    - SimonBoothroyd
